---
- name: Install Vector
  become: true
  become_method: su
  ansible.builtin.apt:
    deb: "https://packages.timber.io/vector/{{ package_version }}/vector_{{ package_version }}-1_amd64.deb"
  notify:
    - Restart vector
  tags: [install]

- name: Copy config
  become: true
  ansible.builtin.template:
    src: "{{ vector_template }}"
    dest: "{{ vector_config_file }}"
    mode: 0644
  notify: Restart vector
  tags: [install]
