---
- name: Install Vector
  become: true
  ansible.builtin.yum:
    name: "https://packages.timber.io/vector/{{ package_version }}/vector-{{ package_version }}-1.{{ arch }}.rpm"
    state: present
    disable_gpg_check: yes # package is not signed
  notify:
    - Restart vector
  tags: [install]

- name: Copy config
  become: true
  ansible.builtin.template:
    src: "{{ vector_template }}"
    dest: "{{ vector_config_file }}"
    mode: 0644
  notify: Restart vector
  tags: [install]

