---
#- name: Restart nginx
#  become: true
##  become_method: su
#  ansible.builtin.service:
#    state: restarted
#    daemon_reload: yes
#    name: nginx

- name: Restart vector
  become: true
#  become_method: sudo
  ansible.builtin.service:
    state: restarted
    daemon_reload: yes
    name: vector