---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu_podman
    image: ubuntu:latest
    privileged: true
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: podman
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
verifier:
  name: ansible


