---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_latest
    image: ubuntu:latest
    dockerfile: ../resources/Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible
